feat: Add feature to store custom_files and config in a subdir for each experiment
aws-deepracer-community/deepracer-for-cloud pull request #165
Opened 2024-05-01 10:28 UTC by mattcamp

The feature enables each training session to have it's config and custom_files stored within a subdir under `experiments/`.

This simplifies being able to locate the config and files that were used for a particular training session. 

An additional flag is added to system.env to control the experiment name, which when set will cause the rest of the config to be loaded from `$DR_DIR/experiments/<experiment_name>/run.env` and `$DR_DIR/experiments/<experiment_name>/custom_files/`.

2024-05-03 12:19 UTC, larsll commented
Question; does things like `dr-increment-training` and the `-1` flag to `dr-upload-model` work?

2024-05-03 16:24 UTC, mattcamp commented
> Question; does things like `dr-increment-training` and the `-1` flag to `dr-upload-model` work?

Yes, they work fine, although the increment-training will just update the current run.env inside the same experiment folder.

I plan to add another command to increment the whole experiment folder which will also update the DR_EXPERIMENT_NAME and increment model prefix + set pretrained prefix.

2024-12-11 18:32 UTC, larsll requested changes
Currently we are using `bin/activate.sh` as default, but it also supports `bin/activate.sh run-1.env` as an example; rather than having it in system.env, could we have it as `bin/activate.sh -e <experiment>`?

2024-12-11 18:32 UTC, larsll commented on defaults/template-system.env
> +# DR_EXPERIMENT_NAME=
Would this not better be a run.env variable?

2026-04-25 12:37 UTC, larsll commented
@copilot Please review this and come with recommendations as to  how to integrate it into the latest version of the code.

2026-04-25 14:35 UTC, merged