Fix: Replacing unsupported flag on docker compose command
aws-deepracer-community/deepracer-for-cloud pull request #172
Opened 2024-05-10 02:45 UTC by joaocarvoli

Fixing the error `unsupported flag -c` on `docker compose` up command. This error happened because var DR_DOCKER_STYLE only considered `swarm` but not the else (`compose`). The `docker compose` uses a different flag to up multiple docker images.

The solution replaces the `-c` occurrences with `-f`.

2024-05-10 09:30 UTC, larsll reviewed
What Docker version has this been tested with? We know that Docker is changing the flags from version to version, and this might cause compatibility issues.

2024-05-10 12:37 UTC, joaocarvoli commented
```bash
docker compose version && docker --version
> Docker Compose version v2.3.3
> Docker version 26.1.2, build 211e74b
```

So if the problem can be related to the version of `docker compose` or `docker` running on the user machine, should we specify on docs or treat this flag based on this dependencies version?

2024-05-13 05:34 UTC, larsll commented
We have updated `prepare.sh` to use the Ubuntu included docker.io, not the separately provided `docker-ce`.

On Ubuntu 22.04 I have installed:
```docker-buildx/jammy-updates,jammy-security,now 0.11.2-0ubuntu1~22.04.2 amd64 [installed]
docker-compose-v2/jammy-updates,now 2.20.2+ds1-0ubuntu1~22.04.1 amd64 [installed]
docker.io/jammy-updates,now 24.0.5-0ubuntu1~22.04.1 amd64 [installed]
nvidia-docker2/unknown,now 2.14.0-1 all [installed]```

Any PR would have to be compatible with Docker 24.

Please also provide information about what the actual problem is -- what was the wrong value? Normally the COMPOSE_FILES get put together using `DR_DOCKER_FILE_SEP`, so the root cause (and fix) would be somewhere else.

See https://github.com/aws-deepracer-community/deepracer-for-cloud/blob/2e3e61bd7a286a4cbc8c246a0c3f6568e9fdd3c1/scripts/training/start.sh#L118 as an example.

2024-05-13 06:23 UTC, larsll requested changes
See previous comment.

2024-05-15 16:10 UTC, joaocarvoli commented
Ok, I already had `docker` and `docker-compose` before the DRfC. If you are saying that the docker version the user uses impacts the behavior of the DRfC it should at least be indicated on the requirements doc, not?

About the problem, it does not happen in another situation, for example on `/scripts/stop.sh`:

```bash
...
# Check if we will use Docker Swarm or Docker Compose
if [[ "${DR_DOCKER_STYLE,,}" == "swarm" ]]; then
    docker stack rm $STACK_NAME
else
    COMPOSE_FILES=$(echo ${DR_TRAIN_COMPOSE_FILE} | cut -f1-2 -d\ )
    export DR_CURRENT_PARAMS_FILE=""
    export ROBOMAKER_COMMAND=""
    docker compose $COMPOSE_FILES -p $STACK_NAME down
fi
...
```

This var `$COMPOSE_FILES` uses the correct `-f` flag to select the desired `docker-compose.yml` file.
My solution corrects where it should happen automatically but is not happening currently.

2024-05-16 20:23 UTC, larsll requested changes
To be convince that using `sed` in this place is the right solution I need to see the bug; please provide `system.env`, `run.env` files and the output of `env` command to actually see that there are -f/-c mix-ups in the input. The problem should be fixed at the source...

2024-05-17 17:42 UTC, joaocarvoli commented
I want to apologize for the pull request I opened regarding the problem with the docker-compose flag. It seems that the issue has resolved itself, and I'm not entirely sure what caused the resolution. As such, the pull request is no longer necessary.

Thank you for your understanding and patience. I appreciate the time you took to review the pull request, and I'm sorry for any inconvenience this may have caused.

2024-05-17 17:43 UTC, joaocarvoli commented
Just for you know if you want...

These were the files that I was using during this test.

I just changed the extensions from `.env` to `.txt` to be able to share them.
[run.txt](https://github.com/aws-deepracer-community/deepracer-for-cloud/files/15355195/run.txt)
[system.txt](https://github.com/aws-deepracer-community/deepracer-for-cloud/files/15355196/system.txt)

2024-05-17 17:43 UTC, closed without merging

2024-05-18 09:32 UTC, larsll commented
I suspect the issue could have come from switching from swarm to compose; some variables require the `bin/activate.sh` to be run again to fully take force.

2024-05-20 12:57 UTC, joaocarvoli commented
That makes sense, on my tests I was doing this activation many times and didn't realize when it worked but I found it out when you requested the files last time.